### ISSUE TITLE
Integration of OS-Viewer & OS-Explorer into OBEU

### ISSUE THREAD

**Issue by schmaluk** [openbudgets/platform#18] opened 2016-09-21 14:08 UTC
Hello @pwalsh and @akariv,

here are the differences on the UI which I have identified between the OS-Viewer and the "OBEU-Viewer":
![os-viewer](https://cloud.githubusercontent.com/assets/17597578/18714234/5e8529d4-8015-11e6-9bad-f5a91c7ee8b9.PNG)
![os-viewer_2](https://cloud.githubusercontent.com/assets/17597578/18714235/5e850b3e-8015-11e6-814b-599a93eb16f5.PNG)

and here the differences between the OS-Explorer and the "OBEU-Explorer"
![os-explorer_1](https://cloud.githubusercontent.com/assets/17597578/18714232/5e7fc16a-8015-11e6-9cf1-136304fe1dfd.PNG)
![os-explorer_2](https://cloud.githubusercontent.com/assets/17597578/18714233/5e80fb02-8015-11e6-8de7-c969426d3012.PNG)

So you would advice me to inject the links, the labels & filepath to the logos as environment variables?

Furthermore there are the following, already existing, injectable environment variables for the openspending/os-viewer-image:
- OS_EXTERNAL_ADDRESS=http://eis-openbudgets.iais.fraunhofer.de
- OS_VIEWER_API_HOST=http://eis-openbudgets.iais.fraunhofer.de
- OS_VIEWER_AUTH_HOST=http://next.openspending.org
- OS_VIEWER_SEARCH_HOST=http://eis-openbudgets.iais.fraunhofer.de

According to @larjohn this environment variable might be needed to get corrected:
- OS_VIEWER_AUTH_HOST=http://next.openspending.org

Thanks for your help

**Comment by pwalsh** [comment] 2016-09-21 14:18
@mlukasch yes. some of this we will do as part of general theming, and some can be just general env var config. we'll get back to you next week on specifics.

**Comment by akariv** [comment] 2016-10-05 12:16
This is the correct value:

OS_VIEWER_AUTH_HOST=http://next.openspending.org

**Comment by schmaluk** [comment] 2016-10-14 08:45
@pwalsh @akariv In order to avoid bigger problems regarding the deadline at the end of this month I'll use a fork of the OS-Viewer for further integration into OBEU in order to adapt the OS-Viewer-Frontend. If there is a better suggestion, please let me know.

**Comment by pwalsh** [comment] 2016-10-14 08:55
@mlukasch can you explain what "bigger problems" you are avoiding by forking? 

We've talked about this for 3-4 times on the tech calls, and there has been no further info added here, and no clarity on those calls.

@akariv is working on theming now, but I still do not see what the problems are/are not.

**Comment by schmaluk** [comment] 2016-10-14 09:11
@pwalsh timewise. Would you be able to provide the theming within the following week? by using a fork adaptions can be made. also possible other changes: https://github.com/openspending/openspending/issues/1140 There are 2 weeks left. So I thought that would be better.

**Comment by akariv** [comment] 2016-10-14 09:13
Yes, for sure. I'm working on it right now.

**Comment by schmaluk** [comment] 2016-10-14 09:17
@akariv @pwalsh Glad that you can make it. Thanks.

**Comment by pwalsh** [comment] 2016-10-14 09:24
@mlukasch 

ok, but again, you are not really explaining what you need, or why. 

When we last talked you said you had a problem with auth, which we have no further context on, and we confirmed that the current env var is correct.

So, if there are _bugs_, you need to report them (much) better (even https://github.com/openspending/openspending/issues/1140 is probably not a bug based on current knowledge in the issue there).

If there are _not_ bugs, then you just need theming hooks? 

The above screenshots with red markings don't really explain _what_ you expect to be able to hook into (eg: red box around the logo obviously means something different to the red box around the search and navigation elements of the explorer, but no explanation is given), but you'll be able to follow progress of what we implement at https://github.com/openspending/openspending/issues/1062 as previously linked.

In any event, of course fork the code to do what you need to do, as the team there are getting to this very late in the timeline, or you can wait for the theming hooks from @akariv in the next week, and we can hope they cover exactly what you are planning to do (which is not documented anywhere in full).

**Comment by schmaluk** [comment] 2016-10-14 12:12
@pwalsh For OpenBudgets I'd suggest the following adaptions according the numbers in the screenshots:
1) The "OSViewer"-Logo needs to be changed to the OpenBudgets-Logo.
2) The "Upload Data"-Link should either be removed or direct to the "OpenSpending Packager" at OpenSpending.
3) "Explore Datasets" directs to OpenBudget-Explorer.
Ignore this please:  4) The "Login/Register"-link: It seems that no changes need to be done here from OpenBudgets perspective.
5) The "Data Mine Button" should direct to the URL of the corrresponding dataset in the Indigo application created by @larjohn
6) a)The "Download Data Package"-link should be either removed or trigger the Download of the corresponding ttl-Dump-files at:
http://eis-openbudgets.iais.fraunhofer.de/dumps
b) The "View Raw Source Data" should get either removed or a show a summary of the corresponding ttl-Dump-files in the Browser
7) "OpenSpending" should be replaced by "Openbudgets"
8) The "Open Knowledge"-Logo should either be removed or replaced by the Openbudget-Logo
9) The Links here should be either removed or adapted

Maybe I cant resolve all points in that way within 1 or 2 weeks. 
Lots of those points will be therefore resolved by just removing the content or leaving as it is.
The "DM-Button" & the Link to "OpenBudget-Explorer" are probably the most important changes which need to be done though.

**Comment by pwalsh** [comment] 2016-10-14 12:30
@mlukasch 

all above seems clear - replacing various urls with env vars that can be swapped out.

But `The "Login/Register"-link should work like in OpenSpending` I don't know what you mean. Unless you are planning on developing your own auth handling (which I have not seen any code for...), would you not just use the OS auth functionality? Please explain more what you are actually attempting to do here.

**Comment by schmaluk** [comment] 2016-10-14 12:36
@pwalsh Reusing the Auth used by OpenSpending. This seems to be also convenient from a user perspective since the dataset upload to OpenBudgets is done via OpenSpending anyway and for that a Login into OpenSpending is required afaik.

**Comment by pwalsh** [comment] 2016-10-14 12:37
@mlukasch ok, so, how is it not working? can you provide a bug report, or a full description of actual behaviour/expected behaviour, and so on?

**Comment by schmaluk** [comment] 2016-10-14 12:38
@pwalsh Yes probably I should have excluded that. Sorry.

**Comment by pwalsh** [comment] 2016-10-14 12:46
@mlukasch it is fine, just that in order to help we need information. So, that means that auth does work?

**Comment by schmaluk** [comment] 2016-10-14 13:06
@pwalsh The Viewer at http://eis-openbudgets.iais.fraunhofer.de/viewer/ will need some fix and @larjohn is working on it.
But the Auth seems to be an additional problem of its own according to the Browser logs:
1) GET https://accounts.google.com/o/oauth2/auth
2) GET http://next.openspending.org/oauth/google_callback [HTTP/1.1 302 FOUND 235ms]
3) GET http://next.openspending.org/user/lib
4) GET XHR http://next.openspending.org/user/check
When i click on "Login" a request is sent to http://next.openspending.org/user/check and is responded with: "authenticated: false" on the OBEU-platform although Im logged into the OpenSpending-Platform.

**Comment by schmaluk** [comment] 2016-10-14 13:18
Unlike on http://next.openspending.org/viewer/ the Parameter "jwt" is not sent from http://eis-openbudgets.iais.fraunhofer.de/viewer/ to http://next.openspending.org/user/check

**Comment by pwalsh** [comment] 2016-10-14 13:23
@mlukasch 

I'd say there is a good chance that the various errors here (see the attached screenshot of the Viewer running at Fraunhofer) are breaking other parts of the logic in javascript. That might be one place for you to start debugging the issue. 

Additionally, if the jwt parameter is not being sent, then a login transaction can't succeed, so you should try to work out why it is not being sent to the OS auth check in the first place. 

If there is something that might be specifically related to the OS auth flow, @akariv should be able to chime in, but right now, it looks like you'll have to get rid of those other errors we can see on the Fraunhofer server in order to get to the source of the issue.

<img width="1280" alt="screenshot 2016-10-14 16 16 44" src="https://cloud.githubusercontent.com/assets/791678/19388720/c2cb3552-9229-11e6-8749-09754f5bad9f.png">

**Comment by schmaluk** [comment] 2016-10-14 15:45
@pwalsh @larjohn has implemented a cache which needed to be cleared. So the Auth works now partially at:
**http://eis-openbudgets.iais.fraunhofer.de/viewer/budget-heraklion-revenue-2014__efb44?lang=en**
If I log out, I cannot login anymore. @akariv Maybe you have an idea why? Will look further into it and come back to you when I've found more about that.

One smaller thing that would need adaption is the Profile-link:
![auth](https://cloud.githubusercontent.com/assets/17597578/19393213/118150e6-9234-11e6-8981-6b56f1a7e5c5.PNG)
Atm it directs to /admin. Either we'd need to provide an admin-Page or redirect to the OS-Admin-Page.
But I think that hasnt high priority atm.
Thanks so far for your help.

**Comment by pwalsh** [comment] 2016-10-17 08:58
@mlukasch ( cc @akariv )
- The PR to integrate theming into the Viewer is here, and due to be merged by tomorrow: https://github.com/openspending/os-viewer/pull/137
- A PR for the Explorer will follow

I'll update here when these hit master on each codebase too, but you can also use the branches in advance if needed.

**Comment by schmaluk** [comment] 2016-10-19 15:41
![os_viewer_issues](https://cloud.githubusercontent.com/assets/17597578/19526742/bbf57cf6-9625-11e6-84b1-0e1358bd2a00.PNG)

Hello @pwalsh and @akariv 
thanks for your great work. 
Just 3 issues with the customizing/theming so far which can be observed at http://eis-openbudgets.iais.fraunhofer.de/viewer :
- Major one: 1) I need to configure the DataMining Button, so that it directs to the URL of the selected dataset of @larjohn's Indigo application. Is there any URL pattern for the link (ref or Label of the current selected dataset). That might be answered somewhere in your documentation. But I havent found it so far.
  Another problem with this: If I login in, I dont see the DataMining Button anymore:
  ![os_viewer_issues_2](https://cloud.githubusercontent.com/assets/17597578/19527092/0b5b01c0-9627-11e6-847e-219e84dfa843.PNG)
- Minor one: 2) As described above under Profile the /admin-page doesnt exist. So what would be the right Thing to do here? Can I somehow redirect to the OpenSpending Admin page for that user?
- Really minor one: 3) I couldnt configure the background-Color of that box under 3) as well as the font-color in general. But that isnt really a problem at all for the moment. Just mentioned it for giving some feedback.
- Minor one: 4) The Links of the Data Resources are not configurable atm. If that makes a lot work to implement this so that it directs to the selected dataset, it would be good to be able to hide this section.

I think 2) & 3) are really not critical. But the Datamining Button should be working on the 1st prototype.
Thanks again for your help. 
Maybe those issues can be solved quickly on my side somehow. I'll look further in the meanwhile.

**Comment by akariv** [comment] 2016-10-25 07:30
@mlukasch 

1) I'll add the ability to customise the data mine button, and try to reproduce the issue with it not appearing.
2) You should deploy the os-admin app - it uses the search api to show all the user's datasets, so redirecting to the openspending one would show the wrong results.
3) If you need another colour modified simply add the CSS rule and change the theme json accordingly and issue a pull request.
4) Links for the data resources are received from the datapackage itself - I'll add detailed instructions here soon.

**Comment by akariv** [comment] 2016-10-25 08:32
Some promised comments:
1) You now have the ability to customise the data mine button in the latest master.
4) a. Download url for the package is taken from the 'origin_url' property in the data package
    b. Download urls for the resources is taken from the 'url' or 'path' properties for each of the resources.
See here for an example:
http://next.openspending.org/api/3/info/5df4a7b06a940c992d1c44525daff47b:mexican-federal-budget-iteration-2/package

**Comment by schmaluk** [comment] 2016-10-28 16:21
Thanks @akariv 
I have installed the OS-Admin app at the Fhg Server and customized OS-Explorer with your theming:
http://eis-openbudgets.iais.fraunhofer.de/explorer/
The problem with the Login can be seen on: http://eis-openbudgets.iais.fraunhofer.de/viewer/
I logout but cannot login anymore.
Plus the DataMining Button doesnt show up. I wasnt able to see the updateDataMineUrl-function called: https://github.com/openspending/os-viewer/blob/master/app/front/scripts/directives/package-info/index.js 
Will be back on Wednesday and investigate further.

**Comment by akariv** [comment] 2016-10-29 06:50
@mlukasch both issues were resolved in the latest viewer master - did you rebase recently?
I also added there the ability to customise the data mine URL.

**Comment by schmaluk** [comment] 2016-11-02 12:30
@akariv Have updated repo in the dockerfile. as well as the config. But in the request to http://next.openspending.org/user/check there is no jwt-token set as can be seen here: http://eis-openbudgets.iais.fraunhofer.de/viewer
Unfortunately the DM-Button to the DM-URL only shows up if you are logged in. So a Login is required.
(The jwt token can get appended then as a query parameter to the DM-URL, which wouldnt be required here afaik)

**Comment by akariv** [comment] 2016-11-02 16:32
I managed to login alright, but the problem seems to be related to an
incompatibility with the facts endpoint, that causes an exception to be
raised - that should be fixed (maybe @larjohn will know more).

Regarding the button appearing or not if you're logged in or not - you can
change the template of the URL of the button by modifying the theme.
If {{token}} is not in the URL, then it will appear for unauthenticated
users as well.

On Wed, 2 Nov 2016 at 14:30 mlukasch notifications@github.com wrote:

@akariv https://github.com/akariv Have updated repo in the dockerfile. as
well as the config. But in the request to
http://next.openspending.org/user/check there is no jwt-token set as can be
seen here: http://eis-openbudgets.iais.fraunhofer.de/viewer
Unfortunately the supposed DM-Button only shows up if you are logged in. So
a Login is required.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
https://github.com/openbudgets/platform/issues/18#issuecomment-257850949,
or mute the thread

**Comment by schmaluk** [comment] 2016-11-02 17:22
@akariv thanks for helping
@larjohn The facts endpoint with different responses:
For example:
- field "cells": http://eis-openbudgets.iais.fraunhofer.de/viewer/budget-heraklion-revenue-2014__efb44?lang=en 
- field "cell": http://next.openspending.org/viewer/23cdc48554ae8648deff7837c025d8c0:mohe2016_detailed?lang=en

Just wanted to ask @larjohn what the URL pattern for showing the Indigo app for the selected dataset via the DM-Button would be? Should for all datasets this URL be used: /indigo/#/cube/analytics/globals i.e. /cube/analytics/globals as said in the last meeting (since the timeseries would require multiple datasets)? Or do you expect a specific parameter for the selected dataset in the URL.

**Comment by larjohn** [comment] 2016-11-02 18:53
I have updated the facts endpoint to work in a more predictable way. It also selects default fields if none is defined.

The URL, in general should be /indigo/#/cube/analytics/{datasetName}

This page will contain a collection of applicable analysis algorithms for the specific dataset. Regarding the timeseries algorithm, it could apply to a single dataset, if this dataset spans to multiple years. This is true, for instance, for some Mexican datasets in OpenSpending. In fact, you can switch the endpoint to next.openspending.org and try to use the timeseries there.

For the time being, it is the responsibility of the user to find a meaningful application to a dataset.

**Comment by schmaluk** [comment] 2016-11-03 16:03
@larjohn http://eis-openbudgets.iais.fraunhofer.de/api/3/cubes/budget-heraklion-revenue-2014__efb44/model returns null i.e. no value for the attribute fact_table. 
But this attribute fact_table is supposed to be the datasetName imo. 
That is why the OS-Viewer cannot compose the URL for the DM-Button:
/indigo/#/cube/analytics/{factTable} 
(I hope that the datasetName would be the same as the factTable in the OS-Viewer.)
Here is a sample of the /model-response in the OS-API: 
http://next.openspending.org/api/3/cubes/23cdc48554ae8648deff7837c025d8c0:kbs2015/model
Here is a sample of Rudolf-response for the  /model-endpoint:
http://eis-openbudgets.iais.fraunhofer.de/api/3/cubes/budget-heraklion-revenue-2014__efb44/model
To solve this it would be good if Rudolf can be adapted to return the fact_table-attribute (which should  be the datasetName) for the /model-endpoint?

**Comment by larjohn** [comment] 2016-11-04 12:38
A new commit fixes this latest issue

**Comment by pwalsh** [comment] 2017-05-24 09:54
was done

**Closed as completed by pwalsh** 2017-05-24 09:54 UTC
